In [1]:
## Libraries in Python
# ''':- Python Library is a collection of function and method that 
# allows you to  perform many actions without your code'''

# :- Eaxmples- 1.Numpy, 2.Matplotlib, 3.Pandas


In [2]:
## Python Numpy
#:-Numpy stands for Numerical python and  is the core library for numeric
#       and scientific computing.
# :-'''It Consists of multi-dimensional array objects and a collection
# of routines for processing those arrays, means you can work with X,Y,Z axis'''


In [3]:
#  Creating NumPy Array

# Single-Dimensional Array
import numpy as np
n1 = np.array([10,20,30,40])
print(n1)
print(type(n1))

[10 20 30 40]
<class 'numpy.ndarray'>


In [4]:
# Multi -DImenstional Array

import numpy as np

n2=np.array([[10,20,30,40],[40,30,20,10]])
print(n2)
print(type(n2))

[[10 20 30 40]
 [40 30 20 10]]
<class 'numpy.ndarray'>


In [5]:
# Initializing NumPy Array
# :-Initializing NumPy array with zeros

import numpy as np
n1 = np.zeros((1,2))
n1

array([[0., 0.]])

In [6]:
print(type(n1))

<class 'numpy.ndarray'>


In [7]:
import numpy as np
n1 = np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
print(type(n1))

<class 'numpy.ndarray'>


In [9]:
# Initializing NumPy Array with same number
import numpy as np
n1 =np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [10]:
# Initializing NumPy Array with arange

n1=np.arange(50,101)
n1

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [11]:
n1=np.arange(10,50,5)  # this will give the output from 10 to 50 at intervals or by skippinf 5 characters.
n1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
# Initializing Numpy array with random Numbers

import numpy as np
n1=np.random.randint(1,100,5)
# Random is a sub module in numpy and randint is submodule in random.
# in this code it  will randomly pick 5 numbers from 1 to 100
n1

array([35, 43,  6, 87, 57])

In [13]:
# Numpy _Shape
# :- Checking the Shape of NumPy arrays

import numpy as np
n1 = np.array([[1,2,3],[4,5,6]])
n1

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
n1.shape  # This will tell that array contains 2 rows and 3 column

(2, 3)

In [15]:
n1.shape = (3,2) # to change the shape then use shape function again
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
n1.shape # Dimension can be change by shape functon form (2,3) to (3,2)

(3, 2)

In [17]:
## Joining NumPy Arrays

# :-There are three ways
# 1.  vstack()  - vertical stack
# 2.  hstack()  - horizontal stack
# 3.  column_stack()  - column stack


In [18]:
# Vertical Stack :- vstack()
import numpy as np
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [19]:
# Horizontaly Stack:- hstack()
import numpy as np
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [20]:
# column stack :- column_stack()
import numpy as np
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [25]:
#  Numpy Intersection & Difference

import numpy as np
n1 = np.array([10,30,40,50,60,70,80,90])
n2 = np.array([40,20,50,60,70,10,100,120,110])

In [26]:
np.intersect1d(n1,n2) # Taking out the common numbers between two arrays

array([10, 40, 50, 60, 70])

In [30]:
np.setdiff1d(n1,n2) # Getting unique values from  n1 and removing common values betn n1 nad n2

array([30, 80, 90])

In [28]:
np.setdiff1d(n2,n1) # Getting unique values from  n2 and removing common values betn n1 nad n2

array([ 20, 100, 110, 120])

In [31]:
#  NumPy Arrays Mathematics

#  Addition of NumPy Arrays

import numpy as np
n1 = np.array([10,30])
n2 = np.array([40,20])

np.sum([n1,n2]) # for getting the sum of values in the list arrays

100

In [32]:
np.sum([n1,n2],axis=0) # for geting the sum of columns

array([50, 50])

In [33]:
np.sum([n1,n2],axis=1) # for getting the sum of rows

array([40, 60])

In [35]:
#  Basic Addition
import numpy as np
n1 = np.array([10,20,30])
n1=n1+1
n1

array([11, 21, 31])

In [36]:
# Basic Substraction
import numpy as np
n1 = np.array([10,20,30])
n1=n1-1
n1

array([ 9, 19, 29])

In [38]:
# Basic Multiplication
import numpy as np
n1 = np.array([10,20,30])
n1=n1*2
n1

array([20, 40, 60])

In [39]:
#  Basic Division
import numpy as np
n1 = np.array([10,20,30])
n1=n1/2
n1

array([ 5., 10., 15.])

In [41]:
#  Numpy Math functions

# Mean

import numpy as np
n1 = np.array([10,20,30,40,50,60])
np.mean(n1)

35.0

In [42]:
# Median
np.median(n1)

35.0

In [43]:
# Standard Devistion
np.std(n1)

17.07825127659933

In [44]:
# Example:-
n1=np.random.randint(1,50,10)
n1

array([13, 46, 26, 44, 19, 41,  3, 47, 35, 30])

In [45]:
np.mean(n1)

30.4

In [46]:
np.median(n1)

32.5

In [47]:
np.std(n1)

14.284257068535277

In [48]:

## Numpy Save & Load



In [50]:
#  Saving NumPy Array

import numpy as np
n1=np.array([10,20,30,40,50,60])

np.save('my_numpy',n1)

In [51]:
# Loading NumPy Array  - for loading the saved the array list.
n2=np.load('my_numpy.npy')
n2

array([10, 20, 30, 40, 50, 60])